### ISSUE TITLE
Gems installing at incorrect versions: undefined method `request' for nil:NilClass

### ISSUE THREAD

**Issue by codeblooded** [rubygems/rubygems#4338]
I'm having a problem or would like to suggest a feature.

My current problem is an inability to install gems at a specific version. I am running Ruby 3.0.0 on 13" Macbook Pro (Apple Silicon, M1) using a Terminal with Rosetta. rbenv was installed with homebrew, ruby was installed with rbenv, ruby gems was updated using `gem update --system`.

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.2.7
```

```
$ ruby -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

![2021-02-02 00 04 30](https://user-images.githubusercontent.com/1209285/106570348-97647480-64ea-11eb-8a74-9252dd19a085.gif)

**Comment by codeblooded** [comment]
I can confirm the installation works fine with ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20], so this appears to only be an issue with ruby gems and ruby 3.

**Comment by deivid-rodriguez** [comment]
I can confirm this issue.

The underlying error is that `cocoapods-generate` at version 2.2.1 cannot be installed on ruby 3, because it depends on `cocoapods-disable-podfile-validations ~> 0.1.1`,and the only version of `cocoapods-disable-podfile-validations` satisfying that (0.1.1) needs ruby ~> 2.1.

The problem here is that rubygems is unable to properly explain this and crashes instead.

**Comment by deivid-rodriguez** [comment]
Fixing this issue is more complicated than it seems. To show proper explanation for resolution errors like this, we need to add the current ruby (and rubygems) version as metadata dependencies to the resolution (like bundler does), so that when conflicts happen, they make sense and can explain the error to the user.

In #4110 I implemented a very basic approach of filtering out specs not matching the current ruby (and rubygems) version as they come from the API. However, that approach is not enough here.

I have a WIP branch but it needs a lot of work.

**Comment by iainbeeston** [comment]
I've added an example gem that has this issue too (although simply running gem install as above might be simpler) https://github.com/iainbeeston/gem_testcase

**Comment by hsbt** [comment]
This crash came from the old Molinillo resolver, which was removed when RubyGems migrated to a vendored PubGrub solver in 6592033131. Unsatisfiable resolutions now raise a formatted Gem::DependencyResolutionError instead of dereferencing a nil conflict, so I am closing this as resolved.
