### ISSUE TITLE
undefined method `each' for #<Gem::Specification when attempting bundle exec gem uninstall --force --all some_gem

### ISSUE THREAD

**Issue by Alexand** [rubygems/rubygems#7883]
### Describe the problem as clearly as you can

/cc @deivid-rodriguez 

It looks like https://github.com/rubygems/rubygems/pull/7667 introduced a regression. I have a script calling `bundle exec gem uninstall --force --all grpc`. It used to work fine with RUBYGEMS_VERSION to 3.5.11 and BUNDLER_VERSION to 2.5.11.

I'm trying to bump those versions to RUBYGEMS_VERSION to 3.5.16 and BUNDLER_VERSION to 2.5.16 and getting errors on this command with the newer versions.

I've reproduced this locally, and it looks like it starts failing from 3.5.12, which is when this PR got released.

Here's my investigation thread upstream: https://gitlab.com/gitlab-org/build/CNG/-/merge_requests/1925#note_2010954028

The relevant error log is the following, when running `bundle exec gem uninstall --force --all grpc`:

```ruby
#20 304.7 ERROR:  While executing gem ... (NoMethodError)
#20 304.7     undefined method `each' for #<Gem::Specification:0x00007d[1392](https://gitlab.com/gitlab-renovate-forks/CNG/-/jobs/7401294345#L1392)e779a8 @extension_dir="/srv/gitlab/vendor/bundle/ruby/3.1.0/extensions/x86_64-linux/3.1.0/grpc-1.63.0-x86_64-linux", @full_gem_path="/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/grpc-1.63.0-x86_64-linux", @gem_dir=nil, @ignored=nil, @bin_dir=nil, @cache_dir="/srv/gitlab/vendor/bundle/ruby/3.1.0/cache", @cache_file="/srv/gitlab/vendor/bundle/ruby/3.1.0/cache/grpc-1.63.0-x86_64-linux.gem", @doc_dir="/srv/gitlab/vendor/bundle/ruby/3.1.0/doc/grpc-1.63.0-x86_64-linux", @ri_dir=nil, @spec_dir="/srv/gitlab/vendor/bundle/ruby/3.1.0/specifications", @spec_file="/srv/gitlab/vendor/bundle/ruby/3.1.0/specifications/grpc-1.63.0-x86_64-linux.gemspec", @gems_dir="/srv/gitlab/vendor/bundle/ruby/3.1.0/gems", @base_dir="/srv/gitlab/vendor/bundle/ruby/3.1.0", @loaded=false, @activated=false, @loaded_from="/srv/gitlab/vendor/bundle/ruby/3.1.0/specifications/grpc-1.63.0-x86_64-linux.gemspec", @original_platform="x86_64-linux", @installed_by_version=#<Gem::Version "3.5.16">, @autorequire=nil, @date=2024-04-26 00:00:00 UTC, @description="Send RPCs from Ruby using GRPC", @email="grpc-io@googlegroups.com", @homepage="https://github.com/google/grpc/tree/master/src/ruby", @name="grpc", @post_install_message=nil, @signing_key=nil, @summary="GRPC system in Ruby", @version=#<Gem::Version "1.63.0">, @authors=["gRPC Authors"], @bindir="src/ruby/bin", @cert_chain=[], @dependencies=[<Gem::Dependency type=:runtime name="google-protobuf" requirements="~> 3.25">, <Gem::Dependency type=:runtime name="googleapis-common-protos-types" requirements="~> 1.0">, <Gem::Dependency type=:development name="bundler" requirements=">= 1.9">, <Gem::Dependency type=:development name="facter" requirements="~> 2.4">, <Gem::Dependency type=:development name="logging" requirements="~> 2.0">, <Gem::Dependency type=:development name="simplecov" requirements="~> 0.22">, <Gem::Dependency type=:development name="rake" requirements="~> 13.0">, <Gem::Dependency type=:development name="rake-compiler" requirements="~> 1.2.1">, <Gem::Dependency type=:development name="rake-compiler-dock" requirements="~> 1.4">, <Gem::Dependency type=:development name="rspec" requirements="~> 3.6">, <Gem::Dependency type=:development name="rubocop" requirements="~> 1.41.0">, <Gem::Dependency type=:development name="signet" requirements="~> 0.7">, <Gem::Dependency type=:development name="googleauth" requirements="~> 1.0">], @executables=[], @extensions=[], @extra_rdoc_files=[], @files=[], @licenses=["Apache-2.0"], @metadata={}, @platform="x86_64-linux", @rdoc_options=[], @require_paths=["src/ruby/lib", "src/ruby/bin", "src/ruby/pb"], @required_ruby_version=#<Gem::Requirement:0x00007d1392e76d50 @requirements=[[">=", #<Gem::Version "2.7">], ["<", #<Gem::Version "3.4.dev">]]>, @required_rubygems_version=#<Gem::Requirement:0x00007d1392e772a0 @requirements=[[">=", #<Gem::Version "0">]]>, @requirements=[], @rubygems_version="3.5.9", @specification_version=4, @test_files=[], @new_platform=#<Gem::Platform:0x00007d1392e774f8 @cpu="x86_64", @os="linux", @version=nil>, @full_name="grpc-1.63.0-x86_64-linux", @extensions_dir="/srv/gitlab/vendor/bundle/ruby/3.1.0/extensions/x86_64-linux/3.1.0", @source=#<Bundler::Source::Rubygems:0x12060 locally installed gems>, @bundler_extension_dir="/srv/gitlab/vendor/bundle/ruby/3.1.0/extensions/x86_64-linux/3.1.0/grpc-1.63.0-x86_64-linux" grpc-1.63.0-x86_64-linux>
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/specification.rb:2121:in `method_missing'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/spec_set.rb:103:in `delete'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/specification_record.rb:93:in `remove_spec'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/uninstaller.rb:166:in `uninstall_gem'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/uninstaller.rb:235:in `block in remove_all'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/uninstaller.rb:235:in `each'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/uninstaller.rb:235:in `remove_all'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/uninstaller.rb:122:in `uninstall'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/commands/uninstall_command.rb:197:in `uninstall'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/commands/uninstall_command.rb:183:in `uninstall_gem'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/commands/uninstall_command.rb:178:in `block in uninstall_specific'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/commands/uninstall_command.rb:170:in `each'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/commands/uninstall_command.rb:170:in `uninstall_specific'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/commands/uninstall_command.rb:132:in `execute'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/command.rb:326:in `invoke_with_build_args'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/command_manager.rb:255:in `invoke_command'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/command_manager.rb:194:in `process_args'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/command_manager.rb:152:in `run'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/gem_runner.rb:56:in `run'
#20 304.7 	/usr/bin/gem:12:in `<top (required)>'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/cli/exec.rb:58:in `load'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/cli/exec.rb:58:in `kernel_load'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/cli/exec.rb:23:in `run'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/cli.rb:455:in `exec'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/cli.rb:35:in `dispatch'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/cli.rb:29:in `start'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/exe/bundle:28:in `block in <top (required)>'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/exe/bundle:20:in `<top (required)>'
#20 304.7 	/usr/bin/bundle:25:in `load'
#20 304.7 	/usr/bin/bundle:25:in `<main>'
#20 304.7 Successfully uninstalled grpc-1.63.0-x86_64-linux
```

Any thoughts?

_Originally posted by @Alexand in https://github.com/rubygems/rubygems/issues/7667#issuecomment-2244019782_
            
### Did you try upgrading RubyGems?

I've tried it all the way up to 3.5.16.

### Post steps to reproduce the problem

One can fork the GitLab repository from https://gitlab.com/gitlab-org/gitlab. Then install RubyGems `3.5.11`.  Then run `bundle install`.  Then run `bundle exec gem uninstall --force --all grpc`. It should succeed.

Then do `gem update --system 3.5.12`. Then run `bundle install` again. Then try to run `bundle exec gem uninstall --force --all grpc`. It should fail.

I've tested this with the GitLab repo Gemfile.lock, but I believe it will happen with other gems too. So probably any smaller Gemfile.lock will do.

### Which command did you run?

It's explained above.

### What were you expecting to happen?

Be able to uninstall the grpc gem.

### What actually happened?

Error when uninstalling: undefined method `each' for #<Gem::Specification...

### Run gem env and paste the output below

On my CI it's a linux platform, but I was able to reproduce it also on my mac:

```sh
RubyGems Environment:
  - RUBYGEMS VERSION: 3.5.12
  - RUBY VERSION: 3.2.3 (2024-01-18 patchlevel 157) [arm64-darwin23]
  - INSTALLATION DIRECTORY: /Users/foo/.asdf/installs/ruby/3.2.3/lib/ruby/gems/3.2.0
  - USER INSTALLATION DIRECTORY: /Users/foo/.gem/ruby/3.2.0
  - RUBY EXECUTABLE: /Users/foo/.asdf/installs/ruby/3.2.3/bin/ruby
  - GIT EXECUTABLE: /opt/homebrew/bin/git
  - EXECUTABLE DIRECTORY: /Users/foo/.asdf/installs/ruby/3.2.3/bin
  - SPEC CACHE DIRECTORY: /Users/foo/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/foo/.asdf/installs/ruby/3.2.3/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - arm64-darwin-23
  - GEM PATHS:
     - /Users/foo/.asdf/installs/ruby/3.2.3/lib/ruby/gems/3.2.0
     - /Users/foo/.gem/ruby/3.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/foo/.asdf/installs/ruby/3.2.3/bin
     - /Users/foo/.rd/bin
     - /Users/foo/google-cloud-sdk/bin
     - /Users/foo/.asdf/shims
     - /Users/foo/.asdf/bin
     - /opt/homebrew/bin
     - /opt/homebrew/sbin
     - /usr/local/bin
     - /System/Cryptexes/App/usr/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
     - /Applications/iTerm.app/Contents/Resources/utilities
     - /Users/foo/Library/Application Support/JetBrains/Toolbox/scripts
```
