### ISSUE TITLE
failed compile with atomic-1.1.14.gem

### ISSUE THREAD

**Issue by waldy45** [rubygems/rubygems#658]
HI I'm getting a fail on compile with atomic-1.1.14.gem when installing rails with the following output.  Im using Windows 7 32bit client & ruby 2.0.0-p247

Q:\Ruby200\bin>gem install rails
Fetching: i18n-0.6.5.gem (100%)
Successfully installed i18n-0.6.5
Fetching: multi_json-1.8.0.gem (100%)
Successfully installed multi_json-1.8.0
Fetching: tzinfo-0.3.37.gem (100%)
Successfully installed tzinfo-0.3.37
Fetching: atomic-1.1.14.gem (100%)
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing rails:
        ERROR: Failed to build gem native extension.

```
Q:/Ruby200/bin/ruby.exe extconf.rb
```

creating Makefile

make "DESTDIR="
generating atomic_reference-i386-mingw32.def
compiling atomic_reference.c
atomic_reference.c: In function 'ir_compare_and_set':
atomic_reference.c:75:2: error: #error No CAS operation available for this platf
orm
make: **\* [atomic_reference.o] Error 1

Gem files will remain installed in Q:/Ruby200/lib/ruby/gems/2.0.0/gems/atomic-1.
1.14 for inspection.
Results logged to Q:/Ruby200/lib/ruby/gems/2.0.0/gems/atomic-1.1.14/ext/gem_make
.out

Q:\Ruby200\bin>
