### ISSUE TITLE
2.6.13 regression "undefined method `spec' for"...

### ISSUE THREAD

**Issue by julik** [rubygems/rubygems#2024]
I'm having a problem or would like to suggest a feature.

My current problem is that `bundle install` for Patron on Travis-CI is broken due to a likely regression in Rubygems. Gem installation works on MRI 2.2 and above, but fails on 2.1.5 and 1.9.3. 

This issue is related to https://github.com/bundler/bundler/issues/3558 and is probably a regression either of that, or of related. It manifests itself on `spec` not being available somewhere within Rubygems, and looks like this in the build log:

https://travis-ci.org/toland/patron/jobs/273580018

When doing a verbose bundle install, the error printed points to rubygems (see https://travis-ci.org/toland/patron/builds/282852313):

```
$ ruby --version
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
$ rvm --version
rvm 1.29.2 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]
$ bundle --version
Bundler version 1.7.6
$ gem --version
2.6.13
4.80s$ bundle install --verbose --jobs=1 --retry=1 --path=${BUNDLE_PATH:-vendor/bundle}
HTTP GET https://bundler.rubygems.org/api/v1/dependencies

<snip>

Installing json 1.8.6
0:  json (1.8.6) from /home/travis/build/toland/patron/vendor/bundle/ruby/1.9.1/specifications/json-1.8.6.gemspec
NoMethodError: undefined method `spec' for nil:NilClass
/home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:262:in `spec'
/home/travis/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/source/path/installer.rb:19:in `generate_bin'
/home/travis/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/source/path.rb:190:in `generate_bin'
/home/travis/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/source/path.rb:73:in `install'
/home/travis/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/installer.rb:104:in `block in install_gem_from_spec'
/home/travis/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/rubygems_integration.rb:162:in `with_build_args'
/home/travis/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/installer.rb:103:in `install_gem_from_spec'
/home/travis/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/installer.rb:264:in `block in install_sequentially'
/home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/forwardable.rb:201:in `each'
/home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/forwardable.rb:201:in `each'
/home/travis/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/installer.rb:263:in `install_sequentially'
/home/travis/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/installer.rb:90:in `run'
/home/travis/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/installer.rb:18:in `install'
/home/travis/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/cli/install.rb:79:in `run'
/home/travis/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/cli.rb:145:in `install'
/home/travis/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/vendor/thor/command.rb:27:in `run'
/home/travis/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
/home/travis/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/vendor/thor.rb:363:in `dispatch'
/home/travis/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/vendor/thor/base.rb:440:in `start'
/home/travis/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/cli.rb:9:in `start'
/home/travis/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/bin/bundle:20:in `block in <top (required)>'
/home/travis/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/lib/bundler/friendly_errors.rb:5:in `with_friendly_errors'
/home/travis/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.6/bin/bundle:18:in `<top (required)>'
/home/travis/.rvm/gems/ruby-1.9.3-p551@global/bin/bundle:23:in `load'
/home/travis/.rvm/gems/ruby-1.9.3-p551@global/bin/bundle:23:in `<main>'
/home/travis/.rvm/gems/ruby-1.9.3-p551@global/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-1.9.3-p551@global/bin/ruby_executable_hooks:15:in `<main>'
An error occurred while installing patron (0.10.0), and Bundler cannot continue.
Make sure that `gem install patron -v '0.10.0'` succeeds before bundling.
```

It does point to a specific gem, but after some investigation and playing with versions I narrowed it down to a Rubygems issue and by bisection I arrived at the conclusion that this started happening due to Travis-CI automatically upgrading RubyGems for security reasons - which is a good practice. The issue likely went unnoticed because this only happens on older MRI versions - and yet, for Patron this is essential since we don't want to kill compatibility with older Rubies prematurely. Builds with 2.6.12 succeed for us, whereas builds with 2.6.13 fail on 1.9.3 and on 2.1.5.

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ ruby --version
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
$ rvm --version
rvm 1.29.2 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]
$ bundle --version
Bundler version 1.7.6
$ gem --version
2.6.13
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by colby-swandale** [comment]
You're using a very old version of Bundler. Can you try updating it.

**Comment by julik** [comment]
@colby-swandale that's interesting - indeed when I did this https://travis-ci.org/toland/patron/builds/283234015 it seems everything worked. So it seems that even though Travis-CI forcibly updates rubygems, it does not forcibly update Bundler. Should we open an issue with them?

**Comment by julik** [comment]
Related - https://github.com/travis-ci/travis-ci/issues/8355

**Comment by colby-swandale** [comment]
This does not appear to be an issue with RubyGems so I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
