### ISSUE TITLE
Problem with --ignore-dependencies and local gem install

### ISSUE THREAD

**Issue by headius** [rubygems/rubygems#771]
Started to get some errors in JRuby's CI after updating master to 2.2.0. It seems to be an issue with --ignore-dependencies and installing local gems. I have not done any deeper investigation yet.

```
system ~/projects/jruby $ gem install --ignore-dependencies /Users/headius/.m2/repository/rubygems/jruby-launcher/1.0.19/jruby-launcher-1.0.19.gem --bindir /Users/headius/projects/jruby/test/../bin --backtrace
ERROR:  While executing gem ... (NoMethodError)
    undefined method `full_name' for nil:NilClass
    /Users/headius/projects/jruby/lib/ruby/shared/rubygems/source/local.rb:117:in `download'
    /Users/headius/projects/jruby/lib/ruby/shared/rubygems/commands/install_command.rb:243:in `install_gem_without_dependencies'
    /Users/headius/projects/jruby/lib/ruby/shared/rubygems/commands/install_command.rb:204:in `install_gem'
    /Users/headius/projects/jruby/lib/ruby/shared/rubygems/commands/install_command.rb:259:in `install_gems'
    org/jruby/RubyArray.java:1556:in `each'
    /Users/headius/projects/jruby/lib/ruby/shared/rubygems/commands/install_command.rb:255:in `install_gems'
    /Users/headius/projects/jruby/lib/ruby/shared/rubygems/commands/install_command.rb:171:in `execute'
    /Users/headius/projects/jruby/lib/ruby/shared/rubygems/command.rb:305:in `invoke_with_build_args'
    /Users/headius/projects/jruby/lib/ruby/shared/rubygems/command_manager.rb:167:in `process_args'
    /Users/headius/projects/jruby/lib/ruby/shared/rubygems/command_manager.rb:137:in `run'
    /Users/headius/projects/jruby/lib/ruby/shared/rubygems/gem_runner.rb:54:in `run'
    /Users/headius/projects/jruby/bin/jgem:21:in `(root)'
    org/jruby/RubyKernel.java:881:in `load'
    /Users/headius/projects/jruby/bin/gem:4:in `(root)'

system ~/projects/jruby $ gem install /Users/headius/.m2/repository/rubygems/jruby-launcher/1.0.19/jruby-launcher-1.0.19.gem --bindir /Users/headius/projects/jruby/test/../bin --backtrace
Building native extensions.  This could take a while...
/Users/headius/projects/jruby/lib/ruby/shared/rubygems/ext/ext_conf_builder.rb:42 warning: Tempfile#unlink or delete called on open file; ignoring
Successfully installed jruby-launcher-1.0.19-java
1 gem installed
```
