### PR TITLE
Fix `gem uninstall` unresolved specifications warning

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

```
$ gem install rake && gem uninstall rake --force --all --executables
Successfully installed rake-13.2.1
1 gem installed
Removing rake
Successfully uninstalled rake-13.2.1
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      psych (>= 4.0.0)
      Available/installed versions of this gem:
      - 5.1.2
      - 5.1.1
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
Removing rake
Successfully uninstalled rake-13.2.1
```

## What is your fix for the problem, implemented in this PR?

Don't reset specifications after `gem uninstall`.

In order to achieve that, we need to make sure we work with non materialized (stub) specifications, so that we can call `SpecificationRecord#remove_spec` and keep them up to date after uninstallation.

After this patch:

```
$ gem install rake && gem uninstall rake --force --all --executables
Successfully installed rake-13.2.1
1 gem installed
Removing rake
Successfully uninstalled rake-13.2.1
```

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by Alexand** [comment]
Hi folks. 👋 

It looks like this introduced a regression. I have a script calling `bundle exec gem uninstall --force --all grpc`. Is used to work fine with RUBYGEMS_VERSION to 3.5.11 and BUNDLER_VERSION to 2.5.11.

I'm trying to bump those versions to RUBYGEMS_VERSION to 3.5.16 and BUNDLER_VERSION to 2.5.16 and getting errors on this command.

I've reproduced this locally, and it looks like it starts failing from 3.5.12, which is when this PR got released.

Here's my investigation thread upstream: https://gitlab.com/gitlab-org/build/CNG/-/merge_requests/1925#note_2010954028

The relevant error log is the following, when running `bundle exec gem uninstall --force --all grpc`:

```ruby
#20 304.7 ERROR:  While executing gem ... (NoMethodError)
#20 304.7     undefined method `each' for #<Gem::Specification:0x00007d[1392](https://gitlab.com/gitlab-renovate-forks/CNG/-/jobs/7401294345#L1392)e779a8 @extension_dir="/srv/gitlab/vendor/bundle/ruby/3.1.0/extensions/x86_64-linux/3.1.0/grpc-1.63.0-x86_64-linux", @full_gem_path="/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/grpc-1.63.0-x86_64-linux", @gem_dir=nil, @ignored=nil, @bin_dir=nil, @cache_dir="/srv/gitlab/vendor/bundle/ruby/3.1.0/cache", @cache_file="/srv/gitlab/vendor/bundle/ruby/3.1.0/cache/grpc-1.63.0-x86_64-linux.gem", @doc_dir="/srv/gitlab/vendor/bundle/ruby/3.1.0/doc/grpc-1.63.0-x86_64-linux", @ri_dir=nil, @spec_dir="/srv/gitlab/vendor/bundle/ruby/3.1.0/specifications", @spec_file="/srv/gitlab/vendor/bundle/ruby/3.1.0/specifications/grpc-1.63.0-x86_64-linux.gemspec", @gems_dir="/srv/gitlab/vendor/bundle/ruby/3.1.0/gems", @base_dir="/srv/gitlab/vendor/bundle/ruby/3.1.0", @loaded=false, @activated=false, @loaded_from="/srv/gitlab/vendor/bundle/ruby/3.1.0/specifications/grpc-1.63.0-x86_64-linux.gemspec", @original_platform="x86_64-linux", @installed_by_version=#<Gem::Version "3.5.16">, @autorequire=nil, @date=2024-04-26 00:00:00 UTC, @description="Send RPCs from Ruby using GRPC", @email="grpc-io@googlegroups.com", @homepage="https://github.com/google/grpc/tree/master/src/ruby", @name="grpc", @post_install_message=nil, @signing_key=nil, @summary="GRPC system in Ruby", @version=#<Gem::Version "1.63.0">, @authors=["gRPC Authors"], @bindir="src/ruby/bin", @cert_chain=[], @dependencies=[<Gem::Dependency type=:runtime name="google-protobuf" requirements="~> 3.25">, <Gem::Dependency type=:runtime name="googleapis-common-protos-types" requirements="~> 1.0">, <Gem::Dependency type=:development name="bundler" requirements=">= 1.9">, <Gem::Dependency type=:development name="facter" requirements="~> 2.4">, <Gem::Dependency type=:development name="logging" requirements="~> 2.0">, <Gem::Dependency type=:development name="simplecov" requirements="~> 0.22">, <Gem::Dependency type=:development name="rake" requirements="~> 13.0">, <Gem::Dependency type=:development name="rake-compiler" requirements="~> 1.2.1">, <Gem::Dependency type=:development name="rake-compiler-dock" requirements="~> 1.4">, <Gem::Dependency type=:development name="rspec" requirements="~> 3.6">, <Gem::Dependency type=:development name="rubocop" requirements="~> 1.41.0">, <Gem::Dependency type=:development name="signet" requirements="~> 0.7">, <Gem::Dependency type=:development name="googleauth" requirements="~> 1.0">], @executables=[], @extensions=[], @extra_rdoc_files=[], @files=[], @licenses=["Apache-2.0"], @metadata={}, @platform="x86_64-linux", @rdoc_options=[], @require_paths=["src/ruby/lib", "src/ruby/bin", "src/ruby/pb"], @required_ruby_version=#<Gem::Requirement:0x00007d1392e76d50 @requirements=[[">=", #<Gem::Version "2.7">], ["<", #<Gem::Version "3.4.dev">]]>, @required_rubygems_version=#<Gem::Requirement:0x00007d1392e772a0 @requirements=[[">=", #<Gem::Version "0">]]>, @requirements=[], @rubygems_version="3.5.9", @specification_version=4, @test_files=[], @new_platform=#<Gem::Platform:0x00007d1392e774f8 @cpu="x86_64", @os="linux", @version=nil>, @full_name="grpc-1.63.0-x86_64-linux", @extensions_dir="/srv/gitlab/vendor/bundle/ruby/3.1.0/extensions/x86_64-linux/3.1.0", @source=#<Bundler::Source::Rubygems:0x12060 locally installed gems>, @bundler_extension_dir="/srv/gitlab/vendor/bundle/ruby/3.1.0/extensions/x86_64-linux/3.1.0/grpc-1.63.0-x86_64-linux" grpc-1.63.0-x86_64-linux>
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/specification.rb:2121:in `method_missing'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/spec_set.rb:103:in `delete'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/specification_record.rb:93:in `remove_spec'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/uninstaller.rb:166:in `uninstall_gem'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/uninstaller.rb:235:in `block in remove_all'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/uninstaller.rb:235:in `each'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/uninstaller.rb:235:in `remove_all'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/uninstaller.rb:122:in `uninstall'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/commands/uninstall_command.rb:197:in `uninstall'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/commands/uninstall_command.rb:183:in `uninstall_gem'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/commands/uninstall_command.rb:178:in `block in uninstall_specific'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/commands/uninstall_command.rb:170:in `each'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/commands/uninstall_command.rb:170:in `uninstall_specific'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/commands/uninstall_command.rb:132:in `execute'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/command.rb:326:in `invoke_with_build_args'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/command_manager.rb:255:in `invoke_command'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/command_manager.rb:194:in `process_args'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/command_manager.rb:152:in `run'
#20 304.7 	/usr/lib64/ruby/site_ruby/3.1.0/rubygems/gem_runner.rb:56:in `run'
#20 304.7 	/usr/bin/gem:12:in `<top (required)>'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/cli/exec.rb:58:in `load'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/cli/exec.rb:58:in `kernel_load'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/cli/exec.rb:23:in `run'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/cli.rb:455:in `exec'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/cli.rb:35:in `dispatch'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/cli.rb:29:in `start'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/exe/bundle:28:in `block in <top (required)>'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
#20 304.7 	/srv/gitlab/vendor/bundle/ruby/3.1.0/gems/bundler-2.5.11/exe/bundle:20:in `<top (required)>'
#20 304.7 	/usr/bin/bundle:25:in `load'
#20 304.7 	/usr/bin/bundle:25:in `<main>'
#20 304.7 Successfully uninstalled grpc-1.63.0-x86_64-linux
```

Any thoughts?
