### ISSUE TITLE
`bundle update` fails with NoMethodError when I updated bundler to 2.2.1 from 2.1.4

### ISSUE THREAD

**Issue by upinetree** [rubygems/rubygems#4158]
# Error Report

## Questions

Please fill out answers to these questions, it'll help us figure out
why things are going wrong.

- **What did you do?**

  I updated bundler to 2.2.1 from 2.1.4 and ran the command `/Users/USER/.rbenv/versions/2.6.5/bin/bundle update`

- **What did you expect to happen?**

  I expected Bundler to successfully update the gems using `bundle update`.

- **What happened instead?**

  Instead, what happened was getting NoMethodError and no gems updated.

- **Have you tried any solutions posted on similar issues in our issue tracker, stack overflow, or google?**

  I tried search similar issues but it could not be found.
  Also I tried to remove `ruby` keyword from PLATFORMS section in `Gemfile.lock`, and it worked but I'm not sure why.

- **Have you read our issues document, https://github.com/rubygems/rubygems/blob/master/bundler/doc/contributing/ISSUES.md?**

  Yes.

## Steps to reproduce the problem

```
$ ruby -v
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]

$ gem -v
3.0.3

$ cat Gemfile
source 'https://rubygems.org'

gem 'libv8'

$ bundle _2.1.4_ install
$ bundle _2.2.1_ install
$ bundle _2.2.1_ update
```

Then got the error report and backtrace below.

## Backtrace

```
NoMethodError: undefined method `activated_platforms' for nil:NilClass
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/resolver.rb:160:in `block in search_for'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/resolver.rb:155:in `each'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/resolver.rb:155:in `search_for'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/resolver.rb:278:in `block in verify_gemfile_dependencies_are_found!'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/resolver.rb:275:in `each'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/resolver.rb:275:in `verify_gemfile_dependencies_are_found!'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/resolver.rb:49:in `start'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/resolver.rb:22:in `resolve'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/definition.rb:274:in `resolve'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/definition.rb:175:in `specs'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/definition.rb:163:in `resolve_remotely!'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/installer.rb:306:in `resolve_if_needed'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/installer.rb:83:in `block in run'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/process_lock.rb:12:in `block in lock'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/process_lock.rb:9:in `open'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/process_lock.rb:9:in `lock'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/installer.rb:72:in `run'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/installer.rb:24:in `install'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/cli/update.rb:69:in `run'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/cli.rb:310:in `block in update'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/settings.rb:115:in `temporary'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/cli.rb:309:in `update'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/cli.rb:30:in `dispatch'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/cli.rb:24:in `start'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/exe/bundle:49:in `block in <top (required)>'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
  /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.1/exe/bundle:37:in `<top (required)>'
  /Users/USER/.rbenv/versions/2.6.5/bin/bundle:23:in `load'
  /Users/USER/.rbenv/versions/2.6.5/bin/bundle:23:in `<main>'
```

## Environment

```
Bundler       2.2.1
  Platforms   ruby, x86_64-darwin-18
Ruby          2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]
  Full Path   /Users/USER/.rbenv/versions/2.6.5/bin/ruby
  Config Dir  /Users/USER/.rbenv/versions/2.6.5/etc
RubyGems      3.0.3
  Gem Home    /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0
  Gem Path    /Users/USER/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0:/Users/USER/.gem/ruby/2.6.0
  User Home   /Users/USER
  User Path   /Users/USER/.gem/ruby/2.6.0
  Bin Dir     /Users/USER/.rbenv/versions/2.6.5/bin
OpenSSL
  Compiled    OpenSSL 1.1.1d  10 Sep 2019
  Loaded      OpenSSL 1.1.1h  22 Sep 2020
  Cert File   /usr/local/etc/openssl@1.1/cert.pem
  Cert Dir    /usr/local/etc/openssl@1.1/certs
Tools
  Git         2.28.0
  RVM         not installed
  rbenv       rbenv 1.1.2-36-g60c9339
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2020-12-14
Git SHA           b98d6b2035
Released Version  true
```

## Bundler settings

```
gem.test
  Set for the current user (/Users/USER/.bundle/config): false
gem.mit
  Set for the current user (/Users/USER/.bundle/config): true
gem.coc
  Set for the current user (/Users/USER/.bundle/config): true
list_command
  Set for the current user (/Users/USER/.bundle/config): "true"
```

### Gemfile

```ruby
source 'https://rubygems.org'

gem 'libv8'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    libv8 (8.4.255.0)
    libv8 (8.4.255.0-x86_64-darwin-18)

PLATFORMS
  ruby
  x86_64-darwin-18

DEPENDENCIES
  libv8

BUNDLED WITH
   2.2.1
```

**Comment by upinetree** [comment]
Ruby 2.7.2 also reproduces this error.

```
$ ruby -v
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]

$ gem -v
3.1.4
```

**Comment by deivid-rodriguez** [comment]
Hi @upinetree. I'm unable to reproduce this :(

Could you prepare an isolated environment where this can be reproduced? Like with a `Dockerfile` or something? That might not be possible though since I have the feeling this might be specific to MacOS.

If you fail to reproduce under docker, could you please post the `Gemfile.lock` file created after each step?

**Comment by upinetree** [comment]
Thank you for your comment :)
I prepared an isolated environment with a `Dockerfile` but it couldn't be reproduced like below. So it might be specific to macOS as expected.

```console
$ cat Dockerfile
FROM ruby:2.7.2

COPY Gemfile /tmp/Gemfile
WORKDIR /tmp

RUN gem install bundler -v 2.1.4
RUN gem install bundler -v 2.2.1

$ docker build -t bundler-update .
$ docker run --rm -it bundler-update bash
root@cdc0ac4b28a1:/tmp# ruby -v
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
root@cdc0ac4b28a1:/tmp# gem -v
3.1.4
root@cdc0ac4b28a1:/tmp# cat Gemfile
source 'https://rubygems.org'

gem 'libv8'
root@cdc0ac4b28a1:/tmp# bundle _2.1.4_ install
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 2.1.4
Fetching libv8 8.4.255.0 (x86_64-linux)
Installing libv8 8.4.255.0 (x86_64-linux)
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
root@cdc0ac4b28a1:/tmp# cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    libv8 (8.4.255.0)

PLATFORMS
  ruby

DEPENDENCIES
  libv8

BUNDLED WITH
   2.1.4
root@cdc0ac4b28a1:/tmp# bundle _2.2.1_ install
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 2.2.1
Using libv8 8.4.255.0 (x86_64-linux)
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
root@cdc0ac4b28a1:/tmp# cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    libv8 (8.4.255.0)
    libv8 (8.4.255.0-x86_64-linux)

PLATFORMS
  ruby
  x86_64-linux

DEPENDENCIES
  libv8

BUNDLED WITH
   2.2.1
root@cdc0ac4b28a1:/tmp# bundle _2.2.1_ update
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 2.2.1
Using libv8 8.4.255.0 (x86_64-linux)
Bundle updated!
```

And on the macOS, `Gemfile.lock` after each steps are created like below.

```console
$ bundle _2.1.4_ install
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 2.1.4
Using libv8 8.4.255.0 (x86_64-darwin-19)
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

$ cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    libv8 (8.4.255.0)

PLATFORMS
  ruby

DEPENDENCIES
  libv8

BUNDLED WITH
   2.1.4

$ bundle _2.2.1_ install
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 2.2.1
Using libv8 8.4.255.0 (x86_64-darwin-19)
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

$ cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    libv8 (8.4.255.0)
    libv8 (8.4.255.0-x86_64-darwin-19)

PLATFORMS
  ruby
  x86_64-darwin-19

DEPENDENCIES
  libv8

BUNDLED WITH
   2.2.1

$ bundle _2.2.1_ update
Fetching gem metadata from https://rubygems.org/.
--- ERROR REPORT TEMPLATE -------------------------------------------------------
# Error Report
(snip)
```

**Comment by deivid-rodriguez** [comment]
Thanks! I had another idea. Can you prepare a github actions workflow that runs under MacOS, and reproduces the error?

**Comment by deivid-rodriguez** [comment]
I couldn't figure out what's wrong for the intermediate lockfiles.

Another question. Once the command fails, if fails again in the same way if you rerun it. Correct? How about `bundle _2.2.1_ lock --update`? Does it fail similarly?

**Comment by upinetree** [comment]
> Can you prepare a github actions workflow that runs under MacOS, and reproduces the error?

OK, I will try it! (It might be tomorrow)

> Once the command fails, if fails again in the same way if you rerun it. Correct?

Yes, it fails again.

> How about `bundle _2.2.1_ lock --update`? Does it fail similarly?

Yes. It fails with same error ``NoMethodError: undefined method `activated_platforms' for nil:NilClass``

**Comment by deivid-rodriguez** [comment]
Ok, so, tecnically, the first `bundle install` commands shouldn't be needed since `bundle lock` only uses the lockfile.

**Comment by deivid-rodriguez** [comment]
Yay! https://github.com/rubygems/rubygems/runs/1564552145?check_suite_focus=true

**Comment by deivid-rodriguez** [comment]
I'm currently investigating the issue, it shouldn't be too hard to fix. I can take it from here, thanks for letting me know about this!

**Comment by deivid-rodriguez** [comment]
@upinetree I figured it out, #4163 should fix it!

**Comment by upinetree** [comment]
@deivid-rodriguez Wow, that's great! Thanks for the fix!
