### ISSUE TITLE
'gem server' causes NameError when loading command 'server'

### ISSUE THREAD

**Issue by s2k** [rubygems/rubygems#5333]
# Environment

```
> gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.5
  - RUBY VERSION: 3.1.0 (2021-12-25 patchlevel 0) [x86_64-darwin21]
  - INSTALLATION DIRECTORY: /Users/stephan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0
  - USER INSTALLATION DIRECTORY: /Users/stephan/.gem/ruby/3.1.0
  - RUBY EXECUTABLE: /Users/stephan/.asdf/installs/ruby/3.1.0/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /Users/stephan/.asdf/installs/ruby/3.1.0/bin
  - SPEC CACHE DIRECTORY: /Users/stephan/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/stephan/.asdf/installs/ruby/3.1.0/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-darwin-21
  - GEM PATHS:
     - /Users/stephan/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0
     - /Users/stephan/.gem/ruby/3.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["https://rubygems.org/"]
     - "gem" => "--omg"
     - "benchmark" => false
     - "install" => "--rdoc --ri --document=yri"
     - "update" => "--rdoc --ri --document=yri"
     - "rdoc" => "--all -N --ri"
  - REMOTE SOURCES:
     - https://rubygems.org/
```

```
> gem list gems

*** LOCAL GEMS ***

rubygems-server (0.1.0)
rubygems-update (3.3.6, 3.3.5)
```

# Behaviour

Trying to start the Rubygems server causes an error:

```
> gem server
ERROR:  Loading command: server (NameError)
	uninitialized constant Gem::Commands::ServerCommand::OptionParser

    OptionParser.accept :Port do |port|
    ^^^^^^^^^^^^
ERROR:  While executing gem ... (NoMethodError)
    undefined method `deprecated?' for nil:NilClass

      cmd.deprecation_warning if cmd.deprecated?
                                    ^^^^^^^^^^^^
```

# Further observation

* The command works nicely in Ruby 2.7.5 (which I also installed via `asdf`)
* It causes the same error message, when using Ruby 3.0.3 (after additionally running `gem install rubygems-server`

Since it worked in 2.7.5, I expect the command to also work in Ruby 3.1.0.

**Comment by deivid-rodriguez** [comment]
I think this is because `RubyGems` no longer loads `optparse` by default since #4881. You can verify this by downgrading to RubyGems 3.2.30 (`gem update --system 3.2.30`). The `rubygems-server` plugin should be updated to load `opt parse` explicitly.

**Comment by s2k** [comment]
Thanks @deivid-rodriguez. 
You're right: The command works, when using rubygems 3.2.20.
