### ISSUE TITLE
RubyGems 2.6.0 - undefined method `split' for Array

### ISSUE THREAD

**Issue by morgoth** [rubygems/rubygems#1511]
I'm having a problem after updating rubygems to 2.6.0.
I'm getting error when launching rails console
```
/home/wojtek/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/path_support.rb:50:in `split_gem_path': undefined method `split' for #<Array:0x0055e18e292fc8> (NoMethodError)
	from /home/wojtek/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/path_support.rb:32:in `initialize'
	from /home/wojtek/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems.rb:351:in `new'
	from /home/wojtek/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems.rb:351:in `paths='
```

Here are my current envrionment details:

```
$ gem env version
2.6.0
```

I didn't investigate it further yet.

**Comment by morgoth** [comment]
I still cannot figure it out.
After adding `puts env["GEM_PATH"].inspect` in https://github.com/rubygems/rubygems/blob/v2.6.0/lib/rubygems/path_support.rb#L31
I got output:
```
nil
nil
"/home/wojtek/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0:/home/wojtek/.gem/ruby/2.3.0"
"/home/wojtek/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0:/home/wojtek/.gem/ruby/2.3.0"
"/home/wojtek/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0:/home/wojtek/.gem/ruby/2.3.0"
"/home/wojtek/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0:/home/wojtek/.gem/ruby/2.3.0"
"/home/wojtek/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0:/home/wojtek/.gem/ruby/2.3.0"
["/home/wojtek/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0", "/home/wojtek/.gem/ruby/2.3.0"]
/home/wojtek/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/path_support.rb:53:in `split_gem_path': undefined method `split' for #<Array:0x00558f83096ad8> (NoMethodError)
```

**Comment by morgoth** [comment]
I found it!
It's caused by `spring` gem which sets gem path to array https://github.com/rails/spring/blob/d746e5181bd3a064a2850ca46abc6f18d4e1054d/lib/spring/client/binstub.rb#L41

I'll work on a fix there

**Comment by rafaelfranca** [comment]
Is not that a breaking change in a minor release? I'm fine with fixing spring but if it accepted an Array in 2.5, 2.6 should at least warn that it is not being accepted in future versions and remove in the next version.

**Comment by rafaelfranca** [comment]
We were aware that it is not a backward compatible change. See the description https://github.com/rubygems/rubygems/pull/1094. So :+1:, just wanted to check if it was a conscious choice.

**Comment by morgoth** [comment]
Fixed in spring 1.6.4
Note for affected people:
After updating spring gem, run `bundle exec spring binstub --all` to regenerate existing binstubs

**Comment by indirect** [comment]
This is addressed in #1514, which restores the behavior spring needs and prints a deprecation warning. We'll release it in 2.6.1 shortly.

**Comment by mirzalazuardi** [comment]
wont work on my mac. so i downgrade to my previous version

**Comment by indirect** [comment]
@mirzalazuardi please try 2.6.1, it should work

**Comment by drewmoore** [comment]
`spring rails s` worked for me. I'm using rvm.
