### ISSUE TITLE
GVim+Ruby breaks on 1.8x for file open: NoMethodError: 'add'

### ISSUE THREAD

**Issue by klauern** [rubygems/rubygems#161]
I wanted to report this since I only saw it happen when I upgraded RubyGems from 1.7.1 to 1.8.x.  When running GVim with Ruby bindings, if I open a ruby file, I get this error:

```
Vim(ruby):NoMethodError: undefined method `add' for "C:/Ruby1.9.2/lib/ruby/gems/1.9.1":String
```

But if I downgrade back to `1.7.1`, this error never comes up.
