### ISSUE TITLE
NoMethodError: undefined method `spec' for nil:NilClass

### ISSUE THREAD

**Issue by vicvega** [rubygems/rubygems#1419]
I run in this issue while using travis-ci to test a gem (called `chaltron`) I'm working on.
When installing all required gems, before running tests I get a
```
NoMethodError: undefined method `spec' for nil:NilClass
```

With gem version 2.4.5 all works well:
```
$ gem --version
2.4.5
...
Installing sass-rails 5.0.4
Installing rails 4.2.5
Installing turbolinks 2.5.3
Installing devise 3.5.3

Using chaltron 0.1.4 from source at .

Your bundle is complete!
```

But with gem version 2.5.1
```
$ gem --version
2.5.1
...
Installing sass-rails 5.0.4
Installing rails 4.2.5
Installing turbolinks 2.5.3
Installing devise 3.5.3

NoMethodError: undefined method `spec' for nil:NilClass

An error occurred while installing chaltron (0.1.4), and Bundler cannot continue.
Make sure that `gem install chaltron -v'0.1.4'` succeeds before bundling.
```
It seems that it cannot use the gem from current path

The error comes with ruby 2.1 and 2.2, while it's working well with ruby 2.0

The full log with gem 2.5.1 is here (ruby 2.0 working, 2.1 and 2.2 not working) https://travis-ci.org/vicvega/chaltron/builds/98079488

The full log with gem 2.4.5 is here (ruby 2.0, 2.1 and 2.2 all working) https://travis-ci.org/vicvega/chaltron/builds/98089718

**Comment by RochesterinNYC** [comment]
This sounds like it's related to the following issues: thoughtbot/factory_girl#846 travis-ci/travis-ci#3531.

In short, the bundler version that the Travis uses is very outdated. Running a gem update and install for bundler as a prestep for the Travis build fixes it usually.

**Comment by vicvega** [comment]
Thanks you @RochesterinNYC 
It worked!

**Comment by equivalent** [comment]
for googling people, just do:

`.travis.yml`

```
language: ruby
before_install: gem install bundler
rvm:
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - 2.1.4
  - 2.1.5
  - 2.2.0
  - 2.3.0
  - ruby-head
````

important part is that `before_install: gem install bundler` it will install current bundler [source](https://docs.travis-ci.com/user/languages/ruby)
