### ISSUE TITLE
Unable to downgrade from 3.0.0 to 2.x.0

### ISSUE THREAD

**Issue by HarriMaatta** [rubygems/rubygems#4222]
I'm having a problem or would like to suggest a feature.

My current problem is that I can't downgrade gems from 3.0.0 to 2.7.0 or 2.8.0. ATM tool fastlane doesn't work with 3.0.0 so that is why I need to downgrade this. More about fastlane issue https://github.com/fastlane/fastlane/issues/17884

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
ls -la
total 0
drwxr-xr-x   4 jenkins  admin  128 Dec 31 10:41 .
drwxr-xr-x   5 jenkins  admin  160 Dec 31 09:00 ..
drwxr-xr-x   7 jenkins  admin  224 Dec 31 10:08 2.7.0
drwxr-xr-x  10 jenkins  admin  320 Dec 31 10:41 3.0.0

pwd
/usr/local/lib/ruby/gems

rm -rf 3.0.0

/usr/local/opt/ruby/bin/gem update --system 2.7.0  
Updating rubygems-update
Fetching rubygems-update-2.7.0.gem
Successfully installed rubygems-update-2.7.0
Parsing documentation for rubygems-update-2.7.0
Installing ri documentation for rubygems-update-2.7.0
Installing darkfish documentation for rubygems-update-2.7.0
Done installing documentation for rubygems-update after 25 seconds
Parsing documentation for rubygems-update-2.7.0
Done installing documentation for rubygems-update after 0 seconds
Installing RubyGems 2.7.0
/usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/rubygems/defaults/operating_system.rb:7:in `singleton class': undefined method `default_specifications_dir' for class `#<Class:Gem>' (NameError)
	from /usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/rubygems/defaults/operating_system.rb:2:in `<module:Gem>'
	from /usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/rubygems/defaults/operating_system.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/gems/rubygems-update-2.7.0/lib/rubygems.rb:1390:in `require'
	from /usr/local/lib/ruby/gems/3.0.0/gems/rubygems-update-2.7.0/lib/rubygems.rb:1390:in `<top (required)>'
	from setup.rb:33:in `require'
	from setup.rb:33:in `<main>'
```

```
$ gem env version
3.2.3
```

Environment is macOS with BigSur 11.1. It is used as a CI/CD node so that is why paths are not defaults.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment]
What’s`3.0.0`? Your report seems Ruby ABI version, not RubyGems version.

**Comment by deivid-rodriguez** [comment]
Yeah, I think you're confusing `ruby` (the programing language) with `rubygems` (its package manager). What you want is to downgrade ruby, not rubygems.

**Comment by HarriMaatta** [comment]
Yep. Messed up things. I can close this and say sorry for everyone :)

**Comment by deivid-rodriguez** [comment]
Not a problem, and happy new year!
