### ISSUE TITLE
Undefined method `identifier` when trying to materialize the `SpecSet` on 2.2.8+

### ISSUE THREAD

**Issue by paracycle** [rubygems/rubygems#4394]
### Describe the problem as clearly as you can

Getting the following error when trying to programmatically load gems in the `Gemfile`:
```
/usr/local/bundle/gems/bundler-2.2.8/lib/bundler/lazy_specification.rb:30:in `==': undefined method `identifier' for #<Gem::Dependency:0x0000560869060d20>
```

### Post steps to reproduce the problem

1. Create the `Gemfile` as follows:
	```ruby
	source 'https://rubygems.org'
	
	gem 'sorbet-runtime'
	gem 'sorbet'
	```
 
2. Run `bundle install`.
2. Create a `test.rb` as follows:
	  ```ruby
	  # test.rb
	  gemfile = File.new(Bundler.default_gemfile)
	  lockfile = File.new(Bundler.default_lockfile)
	  definition = Bundler::Dsl.evaluate(gemfile, lockfile, {})
	  
	  specs = definition.locked_gems.specs.to_a
	  
	  puts definition.resolve.materialize(specs)
	  ```

3. Run `bundle _2.2.7_ exec ruby test.rb`. No errors:
	```console
	#<Bundler::SpecSet:0x00005570ff0d1338>
	```
4. Run `bundle _2.2.8_ exec ruby test.rb` (or any version above). Error:
	  ```console
	  Traceback (most recent call last):
	          6: from test.rb:7:in `<main>'
	          5: from /usr/local/bundle/gems/bundler-2.2.8/lib/bundler/spec_set.rb:80:in `materialize'
	          4: from /usr/local/bundle/gems/bundler-2.2.8/lib/bundler/spec_set.rb:20:in `for'
	          3: from /usr/local/bundle/gems/bundler-2.2.8/lib/bundler/spec_set.rb:20:in `loop'
	          2: from /usr/local/bundle/gems/bundler-2.2.8/lib/bundler/spec_set.rb:22:in `block in for'
	          1: from /usr/local/bundle/gems/bundler-2.2.8/lib/bundler/spec_set.rb:22:in `include?'
	  /usr/local/bundle/gems/bundler-2.2.8/lib/bundler/lazy_specification.rb:30:in `==': undefined method `identifier' for #<Gem::Dependency:0x000056523fa47828> (NoMethodError)
	  Did you mean?  identity
	  ```

### Which command did you run?

Listed in the steps to reproduce.

### What were you expecting to happen?

I was expecting to not get an error on 2.2.8+ either

### What actually happened?

Got the error:
```
/usr/local/bundle/gems/bundler-2.2.8/lib/bundler/lazy_specification.rb:30:in `==': undefined method `identifier' for #<Gem::Dependency:0x000056523fa47828> (NoMethodError)
```

### If not included with the output of your command, run `bundle env` and paste the output below

```
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
```

### Gemfile

```ruby
# frozen_string_literal: true

source 'https://rubygems.org'

gem 'sorbet-runtime'
gem 'sorbet'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    sorbet (0.5.6293)
      sorbet-static (= 0.5.6293)
    sorbet-runtime (0.5.6293)
    sorbet-static (0.5.6293-x86_64-linux)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  sorbet
  sorbet-runtime

BUNDLED WITH
   2.2.8
```

**Comment by deivid-rodriguez** [comment]
Hi!

I was really stumped by this issue because it seems like a too common case to be broken without any specs catching it. Bundler does this "dance" internally all the time. But I could perfectly repro the regression :confused:.

Turns out it was introduced by #4297, where we stopped using `set`, and a patch like this "fixes" it:

```diff
diff --git a/bundler/lib/bundler/lazy_specification.rb b/bundler/lib/bundler/lazy_specification.rb
index 04ba2a2364..4ffc068148 100644
--- a/bundler/lib/bundler/lazy_specification.rb
+++ b/bundler/lib/bundler/lazy_specification.rb
@@ -27,11 +27,11 @@ def full_name
     end
 
     def ==(other)
-      identifier == other.identifier
+      self.class === other && identifier == other.identifier
     end
 
     def eql?(other)
-      identifier.eql?(other.identifier)
+      self.class === other && identifier.eql?(other.identifier)
     end
 
     def hash
```

But then I realized that, although this somehow worked, the `materialize` method is supposed to receive dependencies, not specifications :sweat_smile:. You normally resolve a definition, and that gives you a set of "lazy specifications" (specifications with only the bare information needed to resolve). The you can materialize that set of "lazy specifications" into real specifications by using `materialize` and passing it a subset of your dependencies. This parameter is useful when you have groups configured, like `without development` for example, so that you would pass only the dependencies of the groups that you really need to the method.

Anyways, I think that you'd want to do something like this instead

```diff
diff --git a/test.rb b/test.rb
index 8b34dd3..a9fa269 100644
--- a/test.rb
+++ b/test.rb
@@ -3,6 +3,4 @@ gemfile = File.new(Bundler.default_gemfile)
 lockfile = File.new(Bundler.default_lockfile)
 definition = Bundler::Dsl.evaluate(gemfile, lockfile, {})
 
-specs = definition.locked_gems.specs.to_a
-
-puts definition.resolve.materialize(specs)
+puts definition.resolve.materialize(definition.requested_dependencies)
```

Technically just

```diff
diff --git a/test.rb b/test.rb
index 8b34dd3..a9fa269 100644
--- a/test.rb
+++ b/test.rb
@@ -3,6 +3,4 @@ gemfile = File.new(Bundler.default_gemfile)
 lockfile = File.new(Bundler.default_lockfile)
 definition = Bundler::Dsl.evaluate(gemfile, lockfile, {})
 
-specs = definition.locked_gems.specs.to_a
-
-puts definition.resolve.materialize(specs)
+puts definition.specs
```

Would do almost the same thing:

https://github.com/rubygems/rubygems/blob/51403dbf5dfdd3c17d90bd404af9d91d132ed499/bundler/lib/bundler/definition.rb#L172-L191

But it does some extra stuff like adding the specification for "bundler" itself on top, which I guess you don't want.

**Comment by deivid-rodriguez** [comment]
I don't mind adding the patch above to restore working behaviour for you, I just wanted to give some explanation in case you want to do what you're doing differently.

**Comment by paracycle** [comment]
@deivid-rodriguez Thank you so much for the prompt response and super detailed analysis. I had suspected the `set` change being complicit when looking at the changes between 2.2.7 and 2.2.8.

I just want to give you a little more context of what we are trying to achieve in [Tapioca](https://github.com/Shopify/tapioca), to better understand how we should go from here. Tapioca is a gem that tries to load all the gem dependencies (regardless of required groups, etc) declared in the `Gemfile` into memory, so that it can use runtime reflection to figure out the types exported from those gems and serializes them as RBI (Ruby Interface) files.

In order to achieve that, we'd been using basically the code I've summarized above in our gem with the hopes of skipping some of the default behaviour of Bundler, like excluding certain groups based on the config. Not being super proficient with Bundler internals, we've been using the `materialize` call like I've summarized in this bug report, so far. I would love to figure out a better way of doing this, if we can.

Based on what you said about `materialize` expecting dependencies, I think we can also use the following, if you think it makes sense:
```diff
diff --git a/test.rb b/test.rb
index c560144..53d9a74 100644
--- a/test.rb
+++ b/test.rb
@@ -2,6 +2,6 @@ gemfile = File.new(Bundler.default_gemfile)
 lockfile = File.new(Bundler.default_lockfile)
 definition = Bundler::Dsl.evaluate(gemfile, lockfile, {})

-specs = definition.locked_gems.specs.to_a
+deps = definition.locked_gems.dependencies.values

-puts definition.resolve.materialize(specs)
+puts definition.resolve.materialize(deps)
```

Having said all that, I still think that `==` not failing cryptically might be a better default for Bundler, so I would suggest that the patch that is doing the type check before attempting to compare attributes still has value/

**Comment by redapple0** [comment]
I

**Comment by deivid-rodriguez** [comment]
@paracycle Yes, based on what you explain your proposed modification makes sense. And yes, I'll introduce the patch mentioned below the restore the previous behaviour. After all, a set of specifications can be seen as a set of _exact_ dependencies and that's why things previously work as you expected. I'll fix this :+1:.

**Comment by deivid-rodriguez** [comment]
Hei!

I just got back to this and found that this was accidentally fixed by https://github.com/rubygems/rubygems/commit/78f68cf4b753eacfaaefa827456ec135601aa439, which was shipped with bundler 2.2.24, so closing!
