### ISSUE TITLE
Occur `NoMethodError` when `bundler/inline` used 

### ISSUE THREAD

**Issue by y-yagi** [rubygems/rubygems#2041]
I'm having a problem. 

My current problem is occur `NoMethodError` when `bundler/inline` used.
The reproduction script is as follows. 

```ruby 
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "activesupport", "5.0.2"  # Need to specify a gem that has not been installed yet
end

require "minitest/autorun"
```

```
$ ruby script.rb
Fetching gem metadata from https://rubygems.org/..............
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Using concurrent-ruby 1.0.5
Using i18n 0.8.6
Using minitest 5.10.3
Using thread_safe 0.3.6
Using bundler 1.15.4
Using tzinfo 1.2.3
Fetching activesupport 5.0.2
Installing activesupport 5.0.2
Traceback (most recent call last):
	9: from /home/yaginuma/.rbenv/versions/2.5.0-preview1/lib/ruby/gems/2.5.0/gems/minitest-5.10.3/lib/minitest.rb:63:in `block in autorun'
	8: from /home/yaginuma/.rbenv/versions/2.5.0-preview1/lib/ruby/gems/2.5.0/gems/minitest-5.10.3/lib/minitest.rb:121:in `run'
	7: from /home/yaginuma/.rbenv/versions/2.5.0-preview1/lib/ruby/gems/2.5.0/gems/minitest-5.10.3/lib/minitest.rb:92:in `load_plugins'
	6: from /home/yaginuma/.rbenv/versions/2.5.0-preview1/lib/ruby/2.5.0/rubygems.rb:524:in `find_files'
	5: from /home/yaginuma/.rbenv/versions/2.5.0-preview1/lib/ruby/2.5.0/rubygems.rb:524:in `map'
	4: from /home/yaginuma/.rbenv/versions/2.5.0-preview1/lib/ruby/2.5.0/forwardable.rb:229:in `each'
	3: from /home/yaginuma/.rbenv/versions/2.5.0-preview1/lib/ruby/2.5.0/forwardable.rb:229:in `each'
	2: from /home/yaginuma/.rbenv/versions/2.5.0-preview1/lib/ruby/2.5.0/rubygems.rb:525:in `block in find_files'
	1: from /home/yaginuma/.rbenv/versions/2.5.0-preview1/lib/ruby/2.5.0/rubygems/basic_specification.rb:268:in `matches_for_glob'
/home/yaginuma/.rbenv/versions/2.5.0-preview1/lib/ruby/2.5.0/rubygems/basic_specification.rb:278:in `lib_dirs_glob': undefined method `size' for nil:NilClass (NoMethodError) 
``` 

It seems to be related to #2010. After reverting #2010, the error no longer occurs.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:

```
$ ruby -v 
ruby 2.5.0preview1 (2017-10-10 trunk 60153) [x86_64-linux]
$ gem env version
2.6.14
```
Furthermore, since I am using rubygems bundled to ruby 2.5.0preview1, it may be different from the released version.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by shevegen** [comment]
> Furthermore, since I am using rubygems bundled to ruby 2.5.0preview1, it may be different
> from the released version.

I have no idea myself; while I tested ruby-2.5.0 some days ago, I did not test bundler. But I think people may be curious, since the bundler integration happened just somewhat recently and people may want to make the transition smooth (from one stable ruby to another).

**Comment by hsbt** [comment]
@y-yagi Thanks to your report. It caused by https://github.com/rubygems/rubygems/pull/2010 .

I'm going to fix it.
